### ISSUE TITLE
ip6 support

### ISSUE THREAD

**Issue by lafka** [riemann/riemann-ruby-client#25]
The current client explicitly uses `AF_INET` and therefor `riemann-tools`  and similar would not accept raw ip6 addresses or hostnames with no ip4 addresses.

I'v made a preliminary patch at https://github.com/lafka/riemann-ruby-client/commit/7903811c96e1ee6f0460bf9bdb3eb6a96f534c7b, but as I have no knowledge of Ruby or the reason why `AF_INET` was set explicitly some feedback would be great before i make a pull request!

**Comment by jamtur01** [comment]
Closed via #30. Thanks for getting this started! @lafka
