### ISSUE TITLE
Which versions of Ruby?

### ISSUE THREAD

**Issue by brentvukmer** [riemann/riemann-ruby-client#27]
The Riemann Quickstart refers to Ruby 1.9.3.   

I've got 2.3.1 installed on my Mac, and the Quickstart example for using riemann-client is doing this:

``` shell
> irb -r riemann/client
irb(main):001:0>  r = Riemann::Client.new
=> #<Riemann::Client:0x007fab4387bdb0 @options={:host=>"127.0.0.1", :port=>5555, :timeout=>5}, @udp=#<Riemann::Client::UDP:0x007fab4387bd10 @host="127.0.0.1", @port=5555, @max_size=16384>, @tcp=#<Riemann::Client::TCP:0x007fab4387bcc0 @options={:host=>"127.0.0.1", :port=>5555, :timeout=>5}, @locket=#<Monitor:0x007fab4387bc98 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fab4387bbf8>>>>
irb(main):002:0> r << {
irb(main):003:1* host: "www1",
irb(main):004:1* service: "http req",
irb(main):005:1* metric: 2.53,
irb(main):006:1* state: "critical",
irb(main):007:1* description: "Request took 2.53 seconds.",
irb(main):008:1* tags: ["http"]
irb(main):009:1> }
=> nil
irb(main):010:0>  r['service =~ "http%"']
=> []
```

**Comment by damien** [comment]
@brentvukmer I noticed this same issue locally. Seems to be a problem with the UDP transport—explicitly using the TCP transport fixed that for me.

**Comment by smortex** [comment]
Hey, old issue but I try to sort issues…  We just setup CI in the repo against all supported versions of Ruby, and the test suite heavily rely on this to work so if it was broken at some point, it is not anymore with all currently supported versions of Ruby: 2.7, 3.0 and 3.1.  I assume we want the library to work at least with all supported versions of Ruby.

Maybe we can clone this issue?

**Comment by jamtur01** [comment]
Closing - re-open if you have any further issues!
