### ISSUE TITLE
Support micro-seconds resolution

### ISSUE THREAD

**Issue by alexjfisher** [riemann/riemann-ruby-client#28]
Riemann has supported microsecond resolution since [0.2.13](https://github.com/riemann/riemann/releases/tag/0.2.13)

> Added support of time in microsecond resolution in the Riemann
protocol (See time_micros in the Riemann client. If you maintain a Riemann client should update them to support microseconds.

I'm not sure how complicated adding this is, but I think it's a prerequisite for adding support for ms resolution in the logstash output plugin. https://github.com/logstash-plugins/logstash-output-riemann/issues/19

**Comment by mcorbin** [comment]
Adding microseconds resolution should be easy, it's just a new field (time_micros) in the protobuf format which should contains the time in microseconds resolution.
I don't know ruby, but i will try to add it if i found the time.
